### ISSUE TITLE
Timeline "Quick View" oddity with Top Bar Position set

### ISSUE THREAD

**Issue by brendenglynn** [plarus/TimeStyleBBPebble#11]
I've noticed whenever I have Timeline "Quick View" appear with the the Top Bar position set, a Solid bar is added to the top of the screen. It disappears when you dismiss the Quick View Timeline notification.

This does not occur when Bottom Par position is set.

Please see linked photos:

https://imgur.com/a/u5akN

**Comment by plarus** [comment]
Thanks for your feedback.
It looks like that background colors are not updated as it should...

![wovzxwy](https://user-images.githubusercontent.com/16477554/36447633-38f43bbc-1685-11e8-9925-0d6077222ef7.jpg)

**Comment by plarus** [comment]
I have made the correction of this problem.
Will be included in the next release!

**Comment by brendenglynn** [comment]
Fantastic! Thanks for your work!
