### ISSUE TITLE
0.9.0 Not responding

### ISSUE THREAD

**Issue by Leonick** [plarus/TimeStyleBBPebble#2]
Worked at first when I installed the latest version but late last night the watch face just went away and the Pebble just says TimeStyle BB is not responding.

Tried restarting Pebble, made no different.

Removed watchfaces, restarted Pebble and reinstalled, switched to the not responding message before the watch face had even animated in fully.

This is on a Pebble Round.

**Comment by plarus** [comment]
As I do not have any pebble round watch (in fact no pebble at all) I do not know how investigate your problem. The app work properly on the pebble round emulator.

Maybe there is a problem with the application data settings stored on your watch...
It would be interesting to know if the others pebble round users have the same problem!

**Comment by Leonick** [comment]
Tried going back to the earlier releases now but they don't work either.

Any way to clear application data without doing a factory reset?

**Comment by plarus** [comment]
I do not know if there is any other solution to clear application data.
I can force application data incompatibility by increasing data format version.

Is the timestyle app run correctly without problem on your watch?

**Comment by Leonick** [comment]
Yea, the Timestyle version the store works fine. And so did you 0.8.1.

Just did a factory reset, same problem, stopped responding before finished animating in.

**Comment by plarus** [comment]
My 0.8.1 version works fine for you? (except access to configuration web page)
Between 0.8.1 and 0.9.0 I just add the possibility to switch between left/right sidebar and top/bottom bar.

**Comment by Leonick** [comment]
Yes, didn't have any problems with that version (I was the one suggestion round support) though going back to it didn't work after I installed 0.9.0.

Curiously, now after the factory reset going back to 0.8.1 worked despite 0.9.0 still not working.

EDIT: Tried 0.9.0 again, still not responding, was able to revert to 0.8.1 again.

**Comment by Leonick** [comment]
Any leads? Miss that perfect horizontal watchface.

**Comment by plarus** [comment]
May be it will be better with this new version (1.0) ...
It seems that the application may run out of RAM.
This point should be better with this new version.

**Comment by Leonick** [comment]
Yup, 1.0 works. Awesome, thanks!
